from __future__ import annotations
import pathlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ccreator.testbench.builder import TestbenchBuilder


def _format_value(v) -> str:
    return str(v)


def _source_spice_line(src: dict) -> str:
    kind = src['type']
    name = src['name']
    n_plus = src['n+']
    n_minus = src['n-']
    parts = [f'{kind}{name}', n_plus, n_minus]

    dc = src.get('dc')
    ac = src.get('ac')
    sin_spec = src.get('sin')
    pulse_spec = src.get('pulse')

    if dc is not None:
        parts.append(f'dc {_format_value(dc)}')
    if ac is not None:
        parts.append(f'ac {_format_value(ac)}')

    if sin_spec:
        s = sin_spec
        parts.append(f'sin({s.get("offset", 0)} {s.get("amplitude", 1)} '
                      f'{s.get("frequency", 1e3)} '
                      f'{s.get("delay", 0)} {s.get("damping", 0)})')
    elif pulse_spec:
        p = pulse_spec
        parts.append(f'pulse({p.get("initial", 0)} {p.get("pulsed", 1)} '
                      f'{p.get("delay", 0)} {p.get("rise", 1e-9)} '
                      f'{p.get("fall", 1e-9)} {p.get("width", 1e-6)} '
                      f'{p.get("period", 2e-6)})')

    return ' '.join(str(p) for p in parts)


def _subckt_string(circuit, port_order: list[str]) -> str:
    from ccreator.realistic._analog.netlist_builder import NetlistBuilder

    name = type(circuit).__name__
    ports_str = ' '.join(port_order)
    nb = NetlistBuilder(name)
    circuit.build(nb)
    pyspice_circ = nb._pyspice_circuit

    lines = [f'.subckt {name} {ports_str}']
    for element in pyspice_circ.elements:
        lines.append(str(element))
    if pyspice_circ.raw_spice:
        lines.append(pyspice_circ.raw_spice.strip())
    lines.append(f'.ends {name}')
    return '\n'.join(lines)


def to_spice_string(tb: 'TestbenchBuilder') -> str:
    lines = [
        f'* CCreator Testbench: {tb._name}',
        '* Generated by ccreator',
        '',
    ]

    seen_types: set[str] = set()
    for rec in tb._instances:
        type_name = type(rec.circuit).__name__
        if type_name not in seen_types:
            seen_types.add(type_name)
            ports = getattr(rec.circuit, 'ports', [])
            port_order = [p.name for p in ports]
            lines.append(_subckt_string(rec.circuit, port_order))
            lines.append('')

    for src in tb._sources:
        lines.append(_source_spice_line(src))

    for rec in tb._instances:
        type_name = type(rec.circuit).__name__
        ports = getattr(rec.circuit, 'ports', [])
        port_order = [p.name for p in ports]
        nodes = ' '.join(rec.connections.get(p, p) for p in port_order)
        lines.append(f'X{rec.name} {nodes} {type_name}')

    lines.append('')

    for probe in tb._probes:
        lines.append(f'.probe v({probe})')

    for req in tb._analysis:
        if req.kind == 'ac':
            kw = req.kwargs
            variation = kw.get('variation', 'dec')
            points = kw.get('points', 100)
            fstart = kw.get('fstart', 1)
            fstop = kw.get('fstop', 1e6)
            lines.append(f'.ac {variation} {points} {fstart} {fstop}')
        elif req.kind == 'tran':
            kw = req.kwargs
            lines.append(f'.tran {kw["step"]} {kw["end"]}')
        elif req.kind == 'dc':
            kw = req.kwargs
            lines.append(f'.dc {kw["source"]} {kw["start"]} {kw["stop"]} {kw["step"]}')

    lines.append('.end')
    lines.append('')
    return '\n'.join(lines)


def export_testbench_spice(tb: 'TestbenchBuilder', path: str):
    content = to_spice_string(tb)
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)


def build_pyspice_circuit(tb: 'TestbenchBuilder'):
    """Build a PySpice Circuit object for simulation."""
    from PySpice.Spice.Netlist import Circuit
    from ccreator.realistic._analog.netlist_builder import NetlistBuilder, _safe_node

    circ = Circuit(tb._name)

    for rec in tb._instances:
        type_name = type(rec.circuit).__name__
        ports = getattr(rec.circuit, 'ports', [])
        port_order = [p.name for p in ports]
        safe_port_order = [_safe_node(p) for p in port_order]

        from PySpice.Spice.Netlist import SubCircuit as SC
        sub = SC(type_name, *safe_port_order)
        nb = NetlistBuilder(type_name, _pyspice_obj=sub)
        rec.circuit.build(nb)

        circ.subcircuit(sub)

        # Connection nodes also need safe names
        nodes = [_safe_node(rec.connections.get(p, p)) for p in port_order]
        circ.X(rec.name, type_name, *nodes)

    for src in tb._sources:
        kind = src['type']
        name = src['name']
        n_plus = _safe_node(src['n+'])
        n_minus = _safe_node(src['n-'])

        ac = src.get('ac')
        dc = src.get('dc', 0)
        sin_spec = src.get('sin')
        pulse_spec = src.get('pulse')

        # Use raw SPICE for SIN/PULSE sources to avoid PySpice/ngspice version issues
        if sin_spec or pulse_spec:
            line = _source_spice_line(src)
            # Must use safe node names in raw SPICE
            line_parts = line.split()
            line_parts[1] = n_plus
            line_parts[2] = n_minus
            circ.raw_spice += ' '.join(line_parts) + '\n'
        elif kind == 'V':
            if ac is not None:
                circ.V(name, n_plus, n_minus, f'dc {dc} ac {ac}')
            else:
                circ.V(name, n_plus, n_minus, dc)
        elif kind == 'I':
            if ac is not None:
                circ.I(name, n_plus, n_minus, f'dc {dc} ac {ac}')
            else:
                circ.I(name, n_plus, n_minus, dc)

    return circ
