#include "gmid/simulators/ngspice.hpp"
#include "gmid/model_validator.hpp"

#include <cstdio>
#include <cstdlib>
#include <format>
#include <fstream>
#include <sstream>
#include <string>

namespace gmid {

// ---------------------------------------------------------------------------
// Availability check
// ---------------------------------------------------------------------------

bool NgspiceBackend::available() const {
    std::string cmd = ngspice_bin.string() + " -v > /dev/null 2>&1";
    return std::system(cmd.c_str()) == 0;
}

// ---------------------------------------------------------------------------
// Netlist generation
// ---------------------------------------------------------------------------

std::expected<std::filesystem::path, std::string>
NgspiceBackend::write_netlist(const SweepConfig& cfg) const {
    namespace fs = std::filesystem;
    fs::create_directories(cfg.work_dir);

    const auto netlist_path = cfg.work_dir / "sweep.sp";
    const auto data_path    = cfg.work_dir / "sweep_data";

    std::ofstream out(netlist_path);
    if (!out)
        return std::unexpected("cannot write netlist: " + netlist_path.string());

    const double vgs_step = (cfg.vgs_stop - cfg.vgs_start) / std::max(cfg.vgs_steps - 1, 1);
    const double vds_step = (cfg.vds_stop - cfg.vds_start) / std::max(cfg.vds_steps - 1, 1);

    const bool is_mosfet = (cfg.kind == ModelKind::mosfet);

    out << "* gm/id characterisation sweep — generated by GmIDVisualizer\n";

    // Recursively resolve model file + sibling mismatch files into one flat file.
    // This handles sky130 PDK corner files whose .include chains aren't self-contained.
    {
        auto resolved = resolve_model_with_deps(cfg.model_file);
        if (!resolved)
            return std::unexpected("include resolution failed: " + resolved.error());

        const auto resolved_path = cfg.work_dir / "resolved_model.spice";
        std::ofstream resolved_file(resolved_path);
        if (!resolved_file)
            return std::unexpected("cannot write resolved model: " + resolved_path.string());
        resolved_file << *resolved;
        resolved_file.close();

        out << std::format(".include \"{}\"\n", resolved_path.string());
    }
    out << std::format(".temp {}\n", cfg.temp_c);
    // Monte-Carlo / mismatch switch — disable for deterministic sweeps
    out << ".param mc_mm_switch=0\n\n";

    if (is_mosfet) {
        // VSB != 0: bulk gets its own node at -VSB (source stays grounded,
        // so VSB = Vs - Vb = -Vb).
        const bool has_vsb = cfg.vbs_start != 0.0;
        const char* bulk = has_vsb ? "b" : "0";
        if (cfg.subcircuit)
            out << std::format("X1 d g 0 {} {} W={}u L={}u\n",
                               bulk, cfg.device_name, cfg.width_um, cfg.length_um);
        else
            out << std::format("M1 d g 0 {} {} W={}u L={}u\n",
                               bulk, cfg.device_name, cfg.width_um, cfg.length_um);
        out << "Vgs g 0 0\n";
        out << "Vds d 0 0\n";
        if (has_vsb)
            out << std::format("Vbulk b 0 {}\n", -cfg.vbs_start);
        out << "\n";
        out << ".control\n";
        out << std::format("dc Vgs {} {} {} Vds {} {} {}\n",
                           cfg.vgs_start, cfg.vgs_stop, vgs_step,
                           cfg.vds_start, cfg.vds_stop, vds_step);
        // Write only id — gm and gds are computed numerically in C++ to avoid
        // deriv() firing across VDS-block boundaries in the flat wrdata array.
        out << "let id = -i(Vds)\n";
        out << std::format("wrdata {} id\n", data_path.string());
    } else {
        // BJT: correct node names (b = base, c = collector, emitter to GND)
        if (cfg.subcircuit) {
            int pins = subcircuit_pin_count(cfg.model_file, cfg.device_name);
            if (pins <= 3)
                out << std::format("X1 c b 0 {}\n", cfg.device_name);
            else
                out << std::format("X1 c b 0 0 {}\n", cfg.device_name);
        } else {
            out << std::format("Q1 c b 0 {}\n", cfg.device_name);
        }
        out << "Vbe b 0 0\n";
        out << "Vce c 0 0\n\n";
        out << ".control\n";
        out << std::format("dc Vbe {} {} {} Vce {} {} {}\n",
                           cfg.vgs_start, cfg.vgs_stop, vgs_step,
                           cfg.vds_start, cfg.vds_stop, vds_step);
        out << "let ic = -i(Vce)\n";
        out << "let ib = i(Vbe)\n";
        out << std::format("wrdata {} ic ib\n", data_path.string());
    }

    out << "quit\n";
    out << ".endc\n";
    out << ".end\n";

    return netlist_path;
}

// ---------------------------------------------------------------------------
// wrdata parser
//
// ngspice wrdata writes (x_axis, value) pairs for each requested vector,
// so N vectors → 2*N columns per row.
//
// MOSFET layout (2 cols):  vgs  id
// BJT    layout (4 cols):  vbe  ic   vbe  ib
//
// gm and gds are computed numerically in the C++ extractor to avoid
// deriv() firing across VDS-block boundaries in the flat wrdata array.
// ---------------------------------------------------------------------------

std::expected<SweepResult, std::string>
NgspiceBackend::parse_wrdata(const std::filesystem::path& data_file,
                             const SweepConfig& cfg) {
    auto actual = data_file;
    if (!std::filesystem::exists(actual)) {
        actual = std::filesystem::path(data_file.string() + ".data");
        if (!std::filesystem::exists(actual))
            return std::unexpected("wrdata output not found: " + data_file.string());
    }

    std::ifstream in(actual);
    if (!in)
        return std::unexpected("cannot open wrdata file: " + actual.string());

    const std::size_t expect_n =
        static_cast<std::size_t>(cfg.vgs_steps) *
        static_cast<std::size_t>(cfg.vds_steps) *
        static_cast<std::size_t>(std::max(cfg.vbs_steps, 1));

    SweepResult res;
    res.reserve(expect_n);

    const bool is_mosfet = (cfg.kind == ModelKind::mosfet);

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;

        std::istringstream ss(line);

        if (is_mosfet) {
            // 2 cols: (vgs, id)
            double vgs_val, id_val;
            if (!(ss >> vgs_val >> id_val)) continue;

            res.vgs.push_back(vgs_val);
            res.id.push_back(id_val);
            res.gm.push_back(0.0);    // filled numerically in extractor
            res.vds.push_back(0.0);   // back-filled below
            res.vbs.push_back(0.0);
            res.gds.push_back(0.0);   // filled numerically in extractor
            res.cgs.push_back(0.0);
            res.cgd.push_back(0.0);
            res.vth.push_back(0.0);
        } else {
            // 4 cols: (vbe, ic, vbe, ib)
            double vbe_val, ic_val, dummy, ib_val;
            if (!(ss >> vbe_val >> ic_val >> dummy >> ib_val)) continue;

            res.vgs.push_back(vbe_val);
            res.id.push_back(ic_val);
            res.gm.push_back(0.0);    // filled numerically in extractor
            res.vth.push_back(ib_val);   // ib in vth slot for beta computation
            res.vds.push_back(0.0);
            res.vbs.push_back(0.0);
            res.gds.push_back(0.0);
            res.cgs.push_back(0.0);
            res.cgd.push_back(0.0);
        }
    }

    if (res.size() == 0)
        return std::unexpected("no data points parsed from wrdata output");

    // Back-fill vds from sweep structure (outer loop = Vds/Vce)
    const auto n_vgs    = static_cast<std::size_t>(cfg.vgs_steps);
    const double vd_step = (cfg.vds_stop - cfg.vds_start) / std::max(cfg.vds_steps - 1, 1);
    for (std::size_t i = 0; i < res.size(); ++i)
        res.vds[i] = cfg.vds_start + static_cast<double>(i / n_vgs) * vd_step;  // NOLINT(bugprone-integer-division)

    return res;
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

std::expected<SweepResult, std::string>
NgspiceBackend::run(const SweepConfig& cfg) const {
    auto netlist = write_netlist(cfg);
    if (!netlist)
        return std::unexpected(netlist.error());

    const auto log_path = cfg.work_dir / "ngspice.log";
    std::string cmd = std::format("{} -b {} > {} 2>&1",
                                  ngspice_bin.string(),
                                  netlist->string(),
                                  log_path.string());

    int rc = std::system(cmd.c_str());
    if (rc != 0)
        return std::unexpected(std::format("ngspice exited with code {}, see {}",
                                           rc, log_path.string()));

    return parse_wrdata(cfg.work_dir / "sweep_data", cfg);
}

} // namespace gmid
