#include "gmid/simulators/xyce.hpp"
#include "gmid/model_validator.hpp"

#include <cstdlib>
#include <format>
#include <fstream>
#include <sstream>
#include <string>

namespace gmid {

bool XyceBackend::available() const {
    std::string cmd = xyce_bin.string() + " -v > /dev/null 2>&1";
    return std::system(cmd.c_str()) == 0;
}

// ---------------------------------------------------------------------------
// Netlist generation
// ---------------------------------------------------------------------------

std::expected<std::filesystem::path, std::string>
XyceBackend::write_netlist(const SweepConfig& cfg) const {
    namespace fs = std::filesystem;
    fs::create_directories(cfg.work_dir);

    const auto netlist_path = cfg.work_dir / "sweep.cir";

    std::ofstream out(netlist_path);
    if (!out)
        return std::unexpected("cannot write netlist: " + netlist_path.string());

    const double vgs_step = (cfg.vgs_stop - cfg.vgs_start) / std::max(cfg.vgs_steps - 1, 1);
    const double vds_step = (cfg.vds_stop - cfg.vds_start) / std::max(cfg.vds_steps - 1, 1);

    const bool is_mosfet = (cfg.kind == ModelKind::mosfet);

    out << "* gm/id characterisation sweep — generated by GmIDVisualizer\n";

    // Recursively resolve model file + sibling mismatch files into one flat file.
    {
        auto resolved = resolve_model_with_deps(cfg.model_file);
        if (!resolved)
            return std::unexpected("include resolution failed: " + resolved.error());

        const auto resolved_path = cfg.work_dir / "resolved_model.spice";
        std::ofstream resolved_file(resolved_path);
        if (!resolved_file)
            return std::unexpected("cannot write resolved model: " + resolved_path.string());
        resolved_file << *resolved;
        resolved_file.close();

        out << std::format(".include \"{}\"\n", resolved_path.string());
    }
    out << ".param mc_mm_switch=0\n";

    if (is_mosfet) {
        if (cfg.subcircuit)
            out << std::format("X1 d g 0 0 {} W={}u L={}u\n",
                               cfg.device_name, cfg.width_um, cfg.length_um);
        else
            out << std::format("M1 d g 0 0 {} W={}u L={}u\n",
                               cfg.device_name, cfg.width_um, cfg.length_um);
    } else {
        if (cfg.subcircuit) {
            int pins = subcircuit_pin_count(cfg.model_file, cfg.device_name);
            if (pins <= 3)
                out << std::format("X1 c b 0 {}\n", cfg.device_name);
            else
                out << std::format("X1 c b 0 0 {}\n", cfg.device_name);
        } else {
            out << std::format("Q1 c b 0 {}\n", cfg.device_name);
        }
    }

    out << "\nVgs g 0 0\n";
    out << "Vds d 0 0\n\n";

    // Xyce DC sweep
    out << std::format(".dc Vgs {} {} {} Vds {} {} {}\n",
                       cfg.vgs_start, cfg.vgs_stop, vgs_step,
                       cfg.vds_start, cfg.vds_stop, vds_step);

    // Xyce uses .print for output
    const auto prn_path = cfg.work_dir / "sweep.prn";
    out << std::format(".print dc file={} ", prn_path.string());
    if (cfg.subcircuit) {
        // Can't access internal OP params through subcircuit — just print current
        // gm/gds will be computed numerically by the C++ extractor
        if (is_mosfet)
            out << "I(Vds)\n";
        else
            out << "I(Vds) I(Vgs)\n";   // Ic and Ib for BJT
    } else if (is_mosfet) {
        out << "I(Vds) N(M1:gm) N(M1:gds) N(M1:cgs) N(M1:cgd) N(M1:vth)\n";
    } else {
        out << "I(Vds) N(Q1:gm) N(Q1:go) N(Q1:cpi) N(Q1:cmu) 0\n";
    }

    out << ".end\n";

    return netlist_path;
}

// ---------------------------------------------------------------------------
// .prn parser
//
// Xyce .prn format is whitespace-separated columns with a header row.
// ---------------------------------------------------------------------------

std::expected<SweepResult, std::string>
XyceBackend::parse_output(const std::filesystem::path& prn_file,
                          const SweepConfig& cfg) {
    std::ifstream in(prn_file);
    if (!in)
        return std::unexpected("cannot open Xyce output: " + prn_file.string());

    SweepResult res;
    const std::size_t expect_n =
        static_cast<std::size_t>(cfg.vgs_steps) *
        static_cast<std::size_t>(cfg.vds_steps);
    res.reserve(expect_n);

    std::string line;
    bool header_skipped = false;

    while (std::getline(in, line)) {
        if (line.empty()) continue;

        // Skip header and "End of" footer
        if (!header_skipped) {
            if (line[0] == '{' || std::isalpha(static_cast<unsigned char>(line[0]))) {
                header_skipped = true;
                continue;
            }
        }

        if (line.find("End") != std::string::npos) break;

        std::istringstream ss(line);

        if (cfg.subcircuit) {
            // Subcircuit mode: only I(Vds) [+ I(Vgs) for BJT]
            double idx, id;
            if (!(ss >> idx >> id)) continue;
            double ib = 0.0;
            if (cfg.kind == ModelKind::bjt) ss >> ib;

            res.vgs.push_back(0.0);
            res.vds.push_back(0.0);
            res.vbs.push_back(0.0);
            res.id.push_back(id);
            res.gm.push_back(0.0);
            res.gds.push_back(0.0);
            res.cgs.push_back(0.0);
            res.cgd.push_back(0.0);
            res.vth.push_back(ib);   // ib in vth slot for BJT beta
        } else {
            double idx, id, gm, gds, cgs, cgd, vth;
            if (!(ss >> idx >> id >> gm >> gds >> cgs >> cgd >> vth))
                continue;

            res.vgs.push_back(0.0);
            res.vds.push_back(0.0);
            res.vbs.push_back(0.0);
            res.id.push_back(id);
            res.gm.push_back(gm);
            res.gds.push_back(gds);
            res.cgs.push_back(cgs);
            res.cgd.push_back(cgd);
            res.vth.push_back(vth);
        }
    }

    if (res.size() == 0)
        return std::unexpected("no data parsed from Xyce .prn output");

    // Back-fill sweep voltages
    const auto n_vgs = static_cast<std::size_t>(cfg.vgs_steps);
    const double vgs_step = (cfg.vgs_stop - cfg.vgs_start) / std::max(cfg.vgs_steps - 1, 1);
    const double vds_step = (cfg.vds_stop - cfg.vds_start) / std::max(cfg.vds_steps - 1, 1);
    for (std::size_t i = 0; i < res.size(); ++i) {
        res.vgs[i] = cfg.vgs_start + static_cast<double>(i % n_vgs) * vgs_step;
        res.vds[i] = cfg.vds_start + static_cast<double>(i / n_vgs) * vds_step;
    }

    return res;
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

std::expected<SweepResult, std::string>
XyceBackend::run(const SweepConfig& cfg) const {
    auto netlist = write_netlist(cfg);
    if (!netlist)
        return std::unexpected(netlist.error());

    const auto log_path = cfg.work_dir / "xyce.log";
    std::string cmd = std::format("{} {} > {} 2>&1",
                                  xyce_bin.string(),
                                  netlist->string(),
                                  log_path.string());

    int rc = std::system(cmd.c_str());
    if (rc != 0)
        return std::unexpected(std::format("Xyce exited with code {}, see {}",
                                           rc, log_path.string()));

    return parse_output(cfg.work_dir / "sweep.prn", cfg);
}

} // namespace gmid
