from __future__ import annotations
import pathlib
import sympy as sp
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ccreator.behavioral._analog.circuit import BehavioralAnalogCircuit


def _get_tf_coefficients(circuit: 'BehavioralAnalogCircuit'):
    """Extract numerator and denominator polynomial coefficients from transfer_function(s)."""
    s = sp.Symbol('s')
    H = circuit.transfer_function(s)
    H_simplified = sp.simplify(H)
    numer, denom = sp.fraction(sp.together(H_simplified))
    numer_poly = sp.Poly(sp.expand(numer), s)
    denom_poly = sp.Poly(sp.expand(denom), s)
    num_coeffs = [float(c) for c in numer_poly.all_coeffs()]
    den_coeffs = [float(c) for c in denom_poly.all_coeffs()]
    return num_coeffs, den_coeffs


def to_veriloga_string(circuit: 'BehavioralAnalogCircuit') -> str:
    name = type(circuit).__name__
    num_coeffs, den_coeffs = _get_tf_coefficients(circuit)

    ports = getattr(circuit, 'ports', [])
    port_names = [p.name for p in ports]

    # Find input, output, ground ports
    in_port = next((p.name for p in ports if p.direction == 'input'), 'in')
    out_port = next((p.name for p in ports if p.direction == 'output'), 'out')
    gnd_port = next((p.name for p in ports if p.direction == 'inout'), 'gnd')

    def fmt_list(coeffs):
        return '{' + ', '.join(f'{c:.6g}' for c in coeffs) + '}'

    params = getattr(circuit, 'parameters', {})
    param_lines = '\n'.join(
        f'    parameter real {k} = {v};'
        for k, v in params.items()
    )

    lines = [
        '// generated by ccreator',
        '`include "disciplines.vams"',
        f'module {name}({", ".join(port_names)});',
    ]
    for p in ports:
        lines.append(f'    electrical {p.name};')
    if param_lines:
        lines.append(param_lines)
    lines += [
        '    analog begin',
        f'        V({out_port}, {gnd_port}) <+ laplace_nd(V({in_port}, {gnd_port}), {fmt_list(num_coeffs)}, {fmt_list(den_coeffs)});',
        '    end',
        'endmodule',
        '',
    ]
    return '\n'.join(lines)


def export_veriloga(circuit: 'BehavioralAnalogCircuit', path: str):
    content = to_veriloga_string(circuit)
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
