use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::SystemTime;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let examples_dir = manifest_dir.join("../../examples");
    let pyspice_dir = examples_dir.join("pyspice");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=../../examples");

    // Auto-regenerate examples if schemify binary exists and .py sources are newer.
    if let Some(schemify) = find_schemify(&manifest_dir) {
        regen_examples(&schemify, &pyspice_dir, &examples_dir, &out_dir);
    }

    let mut entries: Vec<(String, String, &str)> = Vec::new(); // (display_name, rel_path, kind)

    if let Ok(dir) = fs::read_dir(&examples_dir) {
        for entry in dir.flatten() {
            let path = entry.path();
            let Some(fname) = path.file_name().and_then(|n| n.to_str()).map(String::from) else {
                continue;
            };

            let (stem, kind) = if let Some(s) = fname.strip_suffix(".chn_tb") {
                (s.to_string(), "Testbench")
            } else if let Some(s) = fname.strip_suffix(".chn_prim") {
                (s.to_string(), "Primitive")
            } else if let Some(s) = fname.strip_suffix(".chn") {
                (s.to_string(), "Schematic")
            } else {
                continue;
            };

            let display = stem
                .replace('_', " ")
                .split(' ')
                .map(|w| {
                    let mut c = w.chars();
                    match c.next() {
                        None => String::new(),
                        Some(first) => {
                            let upper: String = first.to_uppercase().collect();
                            upper + c.as_str()
                        }
                    }
                })
                .collect::<Vec<_>>()
                .join(" ");

            entries.push((display, fname, kind));
        }
    }

    entries.sort_by(|a, b| a.2.cmp(b.2).then_with(|| a.0.cmp(&b.0)));

    let mut code = String::from(
        "// Auto-generated by build.rs — do not edit.\n\n\
         pub struct Example {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub content: &'static str,\n\
         \x20   pub kind: ExampleKind,\n\
         }\n\n\
         #[derive(Clone, Copy, PartialEq, Eq)]\n\
         pub enum ExampleKind {\n\
         \x20   Schematic,\n\
         \x20   Testbench,\n\
         \x20   Primitive,\n\
         }\n\n\
         impl ExampleKind {\n\
         \x20   pub fn label(self) -> &'static str {\n\
         \x20       match self {\n\
         \x20           Self::Schematic => \"Schematic\",\n\
         \x20           Self::Testbench => \"Testbench\",\n\
         \x20           Self::Primitive => \"Primitive\",\n\
         \x20       }\n\
         \x20   }\n\
         }\n\n\
         pub fn all() -> &'static [Example] {\n\
         \x20   static EXAMPLES: &[Example] = &[\n",
    );

    for (display, fname, kind) in &entries {
        let abs = examples_dir.join(fname).canonicalize().unwrap();
        let abs_str = abs.display();
        writeln!(
            code,
            "        Example {{ name: {display:?}, content: include_str!({abs_str:?}), kind: ExampleKind::{kind} }},",
        )
        .unwrap();
    }

    code.push_str("    ];\n    EXAMPLES\n}\n");

    fs::write(out_dir.join("examples_generated.rs"), code).unwrap();
}

// ---------------------------------------------------------------------------
// Example auto-regeneration
// ---------------------------------------------------------------------------

fn find_schemify(manifest_dir: &Path) -> Option<PathBuf> {
    let root = manifest_dir.join("../..");
    for profile in ["release", "debug"] {
        let p = root.join(format!("target/{profile}/schemify"));
        if p.exists() {
            return Some(p);
        }
    }
    None
}

/// Find the newest mtime among all `.py` files under `dir` (recursive).
fn newest_py_mtime(dir: &Path) -> Option<SystemTime> {
    let mut newest: Option<SystemTime> = None;
    let Ok(entries) = fs::read_dir(dir) else {
        return None;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(t) = newest_py_mtime(&path) {
                newest = Some(newest.map_or(t, |n: SystemTime| n.max(t)));
            }
        } else if path.extension().is_some_and(|e| e == "py")
            && !entry.file_name().to_string_lossy().starts_with("__")
        {
            println!("cargo:rerun-if-changed={}", path.display());
            if let Ok(t) = fs::metadata(&path).and_then(|m| m.modified()) {
                newest = Some(newest.map_or(t, |n: SystemTime| n.max(t)));
            }
        }
    }
    newest
}

fn regen_examples(schemify: &Path, pyspice_dir: &Path, examples_dir: &Path, out_dir: &Path) {
    let stamp = out_dir.join(".examples_stamp");
    let stamp_time = fs::metadata(&stamp).and_then(|m| m.modified()).ok();
    let newest_py = newest_py_mtime(pyspice_dir);

    let stale = match (newest_py, stamp_time) {
        (Some(py), Some(st)) => py > st,
        (Some(_), None) => true,
        _ => return,
    };
    if !stale {
        return;
    }

    eprintln!("Regenerating examples from PySpice sources...");

    let categories: &[(&str, &[&str])] = &[
        (
            "component",
            &[
                "basic",
                "mosfet",
                "bjt",
                "opamp",
                "digital",
                "power",
                "mixed_signal",
                "bus",
            ],
        ),
        ("testbench", &["testbench"]),
    ];

    let mut imported = 0u32;
    let mut failed = 0u32;

    for (kind, dirs) in categories {
        for dir_name in *dirs {
            let dir = pyspice_dir.join(dir_name);
            if !dir.is_dir() {
                continue;
            }
            let mut py_files: Vec<_> = fs::read_dir(&dir)
                .into_iter()
                .flatten()
                .flatten()
                .filter(|e| {
                    e.path().extension().is_some_and(|ext| ext == "py")
                        && !e.file_name().to_string_lossy().starts_with("__")
                })
                .collect();
            py_files.sort_by_key(|e| e.file_name());

            for entry in &py_files {
                let py_path = entry.path();
                let status = Command::new(schemify)
                    .args(["import-spice", "--import", "-o"])
                    .arg(examples_dir)
                    .arg(&py_path)
                    .arg(kind)
                    .status();

                match status {
                    Ok(s) if s.success() => imported += 1,
                    Ok(_) => {
                        eprintln!(
                            "cargo:warning=Failed to regenerate example from {}",
                            py_path.display()
                        );
                        failed += 1;
                    }
                    Err(e) => {
                        eprintln!(
                            "cargo:warning=Failed to run schemify for {}: {e}",
                            py_path.display()
                        );
                        failed += 1;
                    }
                }
            }
        }
    }

    eprintln!("Examples: {imported} imported, {failed} failed");

    // Touch stamp so we don't re-run until .py files change again.
    let _ = fs::write(&stamp, "");
}
