#!/usr/bin/env python3
# Stimulus: TB RC PySpice Demo
# Backend: ngspice
# Auto-generated by SchemifyRS

import pyspice_rs

# ===== AUTO-GENERATED NETLIST =====
NETLIST = """\
.subckt rc_lowpass in out
R1 in out 1k
C1 out 0 1u
.ends
"""

# ===== USER STIMULUS (edit below this line) =====

circuit = pyspice_rs.Circuit("TB RC PySpice Demo")
circuit.raw_spice(NETLIST)

# Instantiate DUT
circuit.X("dut", "rc_lowpass", "in", "out")

# Input: pulse stimulus
circuit.PulseVoltageSource(
    "in", "in", circuit.gnd,
    initial_value=0, pulsed_value=3.3,
    rise_time=1e-9, fall_time=1e-9,
    pulse_width=500e-6, period=1e-3,
)

# Run transient simulation
sim = circuit.simulator(backend="ngspice")
analysis = sim.transient(step_time=1e-6, end_time=5e-3)

print("Time points:", len(analysis.time))
print("V(out) final:", analysis["out"][-1])
