set base [pwd]
set lvs_netlist 1
set netlist_type spice
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/429086abdacd3499; xschem load {LCC_instances.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/399ec06bed4dae82; xschem load {LM5134A.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/e5e318855e7099e; xschem load {Q1.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/92eef0e07416b835; xschem load {Q2.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/2eb76021f437aa8c; xschem load {SYMBOL_include.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/daeee41f3d4cdf3e; xschem load {classD_amp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/e3fd85b5febbc065; xschem load {cmos_example.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/5377fbbdd1868c45; xschem load {cmos_inv.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/354887389a5b41da; xschem load {diode_1.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/6ff303d88ad149f5; xschem load {dlatch.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/f00b3fbc633995cf; xschem load {doublepin.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/3284681b65ec13af; xschem load {flop.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/9a06196e34a43d9e; xschem load {greycnt.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/464fe463dcd0a34f; xschem load {lm317.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/1589ba09b1059fd5; xschem load {lm337.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/b7deb5197e9c41b5; xschem load {loading.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/455c16cd3c9ae1a4; xschem load {mos_power_ampli.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/bbec24b10223189; xschem load {mos_power_ampli_extracted.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/3b37b65fce5da5dd; xschem load {nand2.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/4e080e793158b058; xschem load {osc.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/25dc2fb93f15be7f; xschem load {plot_manipulation.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/ed247a308d2548c7; xschem load {poweramp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/b2ac806ec127011e; xschem load {poweramp_lcc.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/ca92a1dbaaf2b7f9; xschem load {poweramp_xyce.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/231f864c0ed4fe66; xschem load {pump.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/a4b50d3bc420b1c0; xschem load {rcline.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/6738d438d5f151b6; xschem load {real_capa.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/843f7bb4d6cb9a7e; xschem load {rlc.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/a5fd3bd13579cb8; xschem load {sr_flop.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/2b4518db241e0092; xschem load {switch_rreal.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/81a403de977f37fe; xschem load {tb_symbol_include.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/9a5f0fbaa6d5af2d; xschem load {tb_test_evaluated_param.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/30a28475614bef08; xschem load {tesla.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/26794cf702728fd; xschem load {test_ac.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/2c1200c344f5b9e3; xschem load {test_ac_xyce.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/fe782cf5366b5d7b; xschem load {test_backannotated_subckt.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/b1633ac6e3bc84e3; xschem load {test_bus_tap.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/43b525882ac8c0d7; xschem load {test_doublepin.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/7bce260ad29c9152; xschem load {test_evaluated_param.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/fd3d78da7ce6ff89; xschem load {test_extracted_netlist.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/a28c752967fab174; xschem load {test_jfet.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/d6b38844c2fea299; xschem load {test_lm324.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/901302ee6642bed1; xschem load {test_lvs_ignore.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/57a370ec94e201f6; xschem load {test_ne555.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/37d730813e7b10cb; xschem load {test_nyquist.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/a72d765058618858; xschem load {test_short_option.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/f662289680e0404c; xschem load {xcross.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_core_examples; set netlist_dir $base/test/.tmp_xschem_batch/f4bffbbcd7490a91; xschem load {xnor.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/decred_hash_macro; set netlist_dir $base/test/.tmp_xschem_batch/2e36cc514098c46d; xschem load {decred_controller.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/decred_hash_macro; set netlist_dir $base/test/.tmp_xschem_batch/9d7c540db8356776; xschem load {decred_hash_macro.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/decred_hash_macro; set netlist_dir $base/test/.tmp_xschem_batch/4f4d5280df65d500; xschem load {user_project_wrapper.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/2628fe181e54764f; xschem load {alu.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/1e8cde86f93040b3; xschem load {aludec.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/5d7b0c7bc51fc043; xschem load {controller.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/aa4a6006c3f4fba5; xschem load {datapath.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/66d8ec8fa4412f6e; xschem load {dmem.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/5aca21786a60ac8; xschem load {imem.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/cd26cba27f82b429; xschem load {maindec.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/a14030cc1167eb0c; xschem load {mips.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/bdf4ba609b197b29; xschem load {regfile.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/9c60d2db8ef6a08c; xschem load {sign_extend.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/193e20d122140ef7; xschem load {tb.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/mips_cpu; set netlist_dir $base/test/.tmp_xschem_batch/95efdcdf7aefe9e8; xschem load {top.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/fd7c5f557bb556db; xschem load {LACG.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/a6daf30ea1f6a9eb; xschem load {adder_16bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/48bfc886c59ad77e; xschem load {adder_1bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/2db35241cdb12409; xschem load {adder_256bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/584b35a00429ab4b; xschem load {adder_32bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/3710b4fae10cc0ee; xschem load {adder_4bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/a45cb5b9b837ede3; xschem load {adder_64bit.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/a97b082bbe28c0e7; xschem load {all_sky130_gates.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/d3af930462e4d21e; xschem load {bandgap.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/e0dc45772d07810c; xschem load {bandgap_opamp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/38bd42af9a221dd7; xschem load {charge_pump.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/bce85365ed031a6a; xschem load {charge_pump2.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/fac7b555f6cfc708; xschem load {charge_pump_ideal.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/71ba06d03b6ab2c6; xschem load {charge_pump_phasegen.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/ca95ffaf93d2fff4; xschem load {cla_2bits.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/3d3d2d939db25a97; xschem load {cla_4bits.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/482032bc749c85e2; xschem load {cmos_ac_sweep.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/b655924db633f5d1; xschem load {diode_ngspice.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/ee031863d0fc1afa; xschem load {gain_stage.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/535689f1bf3cd6a4; xschem load {gates.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/6bf345614ff3ba5b; xschem load {gates_sky130.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/6a2186e2f18e7cbd; xschem load {logic_ngspice.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/e013a96b241e1203; xschem load {lvnand.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/dae8151de2b2c05; xschem load {lvtnot.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/b4c0521d92cdbada; xschem load {montecarlo_mismatch_sim.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/24f2019269545aeb; xschem load {n_diffamp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/f7cff461e009a200; xschem load {ngspice_flop.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/59d650942a744bcc; xschem load {not.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/720b7cf444da0c01; xschem load {optimize_delay.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/6a63cf0104625815; xschem load {ota1tb.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/eb162e23bc0239b1; xschem load {passgate.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/8f90b9d9a24aacc0; xschem load {passgate_nlvt.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/c8d8b72d138b85e7; xschem load {simulate_ff.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/7d08c8c5689246fb; xschem load {sky130_mismatch.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/ceb98cd1230d394b; xschem load {sky130_oscillator.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/28d09bbae23edf53; xschem load {srlatch.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/cf7e6df0d7632dda; xschem load {stdcells.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/e5adeed5131b050a; xschem load {stdcells_xspice.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/3af88a0b474f40c9; xschem load {tb_bandgap.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/d0f8db3e6cbc92c8; xschem load {tb_bandgap_opamp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/67ec675cedfad059; xschem load {tb_charge_pump.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/21665a975dbd89e2; xschem load {tb_diff_amp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/b1fd48f8ebaa2bc1; xschem load {tb_ft_test.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/85f9a65769b864f; xschem load {tb_ft_test_2.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/637a8628478520ba; xschem load {tb_reram.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/b756382ceb7deed9; xschem load {test_ac.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/5379b3186ef65124; xschem load {test_analog.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/7164bc3f08998d05; xschem load {test_bipolar.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/58af1b14db16f9e7; xschem load {test_carry_lookahead.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/bf8f255d4f9c7ba8; xschem load {test_comparator.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/d268eee3e79d60c0; xschem load {test_customplot.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/8d8e7f282696c514; xschem load {test_diode.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/1f7b71ffb3a74e01; xschem load {test_ff.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/757f082a7472cec2; xschem load {test_format_override.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/f1e0c7d957fcc5a4; xschem load {test_generators.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/165ec7448ae832dd; xschem load {test_hvl_cells.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/dd599acdfbd162f1; xschem load {test_inv.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/520509cd39042fcb; xschem load {test_lvs_ignore.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/64149dc3c5817f4; xschem load {test_mim_cap.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/c083165e2c721316; xschem load {test_mos_binning.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/f51e684e6116d976; xschem load {test_multisim.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/883f0237fed8be73; xschem load {test_nand2_noschematic.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/663aba5d35f56cbf; xschem load {test_nmos.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/557faae8914fe8f9; xschem load {test_nmos_sizes.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/560d7aeda1e9c7cd; xschem load {test_pmos.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/914b671c11403788; xschem load {test_res.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/2e3880bf44103d32; xschem load {test_s_xfer.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/4cb15540a745f6e; xschem load {test_short_option.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/636de4d13161e05c; xschem load {test_stdcells.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/d82a4d014822278e; xschem load {test_sweep_mos_w.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/6428e600236ca9f6; xschem load {test_sweep_res_l.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/a1c4cf89b09f368a; xschem load {test_varactor.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/c3e179719f2df88f; xschem load {test_vpp_cap.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/sky130_tests; set netlist_dir $base/test/.tmp_xschem_batch/dc55596da553b264; xschem load {zero_opamp.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/xschem_verilog_import; set netlist_dir $base/test/.tmp_xschem_batch/127d2124088255fb; xschem load {audiodac.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/xschem_verilog_import; set netlist_dir $base/test/.tmp_xschem_batch/edcd7ef0f39d13c5; xschem load {counter.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/xschem_verilog_import; set netlist_dir $base/test/.tmp_xschem_batch/2ac8948f9dc10ba6; xschem load {sky130_fd_sc_hvl__lsbuflv2hv_1.sch}; xschem netlist}
catch {cd $base/test/examples/xschem_sky130/xschem_verilog_import; set netlist_dir $base/test/.tmp_xschem_batch/8d2f424f21cfd567; xschem load {spm.sch}; xschem netlist}
xschem exit closewindow force
