use std::fmt::Write;
use std::path::{Path, PathBuf};

use schemify_core::simulation::{SpiceBackend, StimulusLang};

const SPICE_MARKER: &str = "* ===== USER STIMULUS (edit below this line) =====";
const PY_MARKER: &str = "# ===== USER STIMULUS (edit below this line) =====";

/// Derive companion stimulus file path from a `.chn_tb` path.
pub fn stimulus_path(tb_path: &Path, lang: StimulusLang) -> PathBuf {
    let stem = tb_path.file_stem().unwrap_or_default();
    let ext = lang.extension();
    tb_path.with_file_name(format!("{}.{ext}", stem.to_string_lossy()))
}

/// Split a `.spice` stimulus file at the user marker.
/// Returns `(header, user_code)`. If no marker found, all content is header.
pub fn split_spice(content: &str) -> (&str, &str) {
    split_at_marker(content, SPICE_MARKER)
}

/// Split a `.py` stimulus file at the user marker.
pub fn split_py(content: &str) -> (&str, &str) {
    split_at_marker(content, PY_MARKER)
}

fn split_at_marker<'a>(content: &'a str, marker: &str) -> (&'a str, &'a str) {
    if let Some(pos) = content.find(marker) {
        let end = pos + marker.len();
        let user_start = content[end..]
            .find('\n')
            .map(|i| end + i + 1)
            .unwrap_or(content.len());
        (&content[..end], &content[user_start..])
    } else {
        (content, "")
    }
}

/// Generate a `.spice` stimulus file.
///
/// `netlist` = auto-generated subcircuit netlist from the schematic.
/// `user_code` = user-editable stimulus section (preserved across regenerations).
pub fn write_spice_stimulus(
    name: &str,
    lang: StimulusLang,
    backend: SpiceBackend,
    netlist: &str,
    user_code: &str,
) -> String {
    let mut buf = String::with_capacity(1024);
    let _ = writeln!(buf, "* ================================================");
    let _ = writeln!(buf, "* Netlist: {name}");
    let _ = writeln!(
        buf,
        "* Dialect: {} | Backend: {}",
        lang.as_str(),
        backend.as_str()
    );
    let _ = writeln!(
        buf,
        "* Auto-generated by SchemifyRS — DO NOT EDIT above marker"
    );
    let _ = writeln!(buf, "* ================================================");
    if !netlist.is_empty() {
        let _ = writeln!(buf);
        let _ = writeln!(buf, "{}", netlist.trim_end());
    }
    let _ = writeln!(buf);
    let _ = writeln!(buf, "{SPICE_MARKER}");
    let _ = writeln!(buf);
    if user_code.is_empty() {
        let _ = writeln!(buf, "* Add your stimulus code here");
        let _ = writeln!(buf, ".end");
    } else {
        buf.push_str(user_code);
        if !user_code.ends_with('\n') {
            buf.push('\n');
        }
    }
    buf
}

/// Generate a `.py` (PySpice) stimulus file.
pub fn write_py_stimulus(
    name: &str,
    backend: SpiceBackend,
    netlist: &str,
    user_code: &str,
) -> String {
    let mut buf = String::with_capacity(1024);
    let _ = writeln!(buf, "#!/usr/bin/env python3");
    let _ = writeln!(buf, "# Stimulus: {name}");
    let _ = writeln!(buf, "# Backend: {}", backend.as_str());
    let _ = writeln!(buf, "# Auto-generated by SchemifyRS");
    let _ = writeln!(buf);
    let _ = writeln!(buf, "import pyspice_rs");
    let _ = writeln!(buf);
    let _ = writeln!(buf, "# ===== AUTO-GENERATED NETLIST =====");
    let _ = writeln!(buf, "NETLIST = \"\"\"\\");
    for line in netlist.lines() {
        let _ = writeln!(buf, "{line}");
    }
    let _ = writeln!(buf, "\"\"\"");
    let _ = writeln!(buf);
    let _ = writeln!(buf, "{PY_MARKER}");
    let _ = writeln!(buf);
    if user_code.is_empty() {
        let _ = writeln!(buf, "circuit = pyspice_rs.Circuit(\"{name}\")");
        let _ = writeln!(buf, "circuit.raw_spice(NETLIST)");
        let _ = writeln!(buf, "# Add your stimulus code here");
    } else {
        buf.push_str(user_code);
        if !user_code.ends_with('\n') {
            buf.push('\n');
        }
    }
    buf
}

/// Generate or update a companion stimulus file.
///
/// If `existing_content` is provided, preserves the user section.
/// Returns the new file content.
pub fn generate_stimulus(
    name: &str,
    lang: StimulusLang,
    backend: SpiceBackend,
    netlist: &str,
    existing_content: Option<&str>,
) -> String {
    let user_code = existing_content
        .map(|c| {
            if lang.is_python() {
                split_py(c).1
            } else {
                split_spice(c).1
            }
        })
        .unwrap_or("");

    if lang.is_python() {
        write_py_stimulus(name, backend, netlist, user_code)
    } else {
        write_spice_stimulus(name, lang, backend, netlist, user_code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stimulus_path_spice() {
        let p = stimulus_path(Path::new("/a/tb_foo.chn_tb"), StimulusLang::NgSpice);
        assert_eq!(p, PathBuf::from("/a/tb_foo.spice"));
    }

    #[test]
    fn stimulus_path_pyspice() {
        let p = stimulus_path(Path::new("/a/tb_foo.chn_tb"), StimulusLang::PySpice);
        assert_eq!(p, PathBuf::from("/a/tb_foo.py"));
    }

    #[test]
    fn split_spice_roundtrip() {
        let content = write_spice_stimulus(
            "test",
            StimulusLang::NgSpice,
            SpiceBackend::NgSpice,
            ".subckt foo a b\nR1 a b 10k\n.ends",
            "",
        );
        let (header, user) = split_spice(&content);
        assert!(header.contains("DO NOT EDIT"));
        assert!(user.contains("Add your stimulus"));
    }

    #[test]
    fn preserves_user_code() {
        let initial = write_spice_stimulus(
            "test",
            StimulusLang::NgSpice,
            SpiceBackend::NgSpice,
            ".subckt foo a b\nR1 a b 10k\n.ends",
            "",
        );
        let user_edit = initial.replace(
            "* Add your stimulus code here\n.end",
            "Vin a 0 5\n.op\n.end",
        );
        let regenerated = generate_stimulus(
            "test",
            StimulusLang::NgSpice,
            SpiceBackend::NgSpice,
            ".subckt foo a b\nR1 a b 20k\n.ends",
            Some(&user_edit),
        );
        assert!(regenerated.contains("20k"), "netlist updated");
        assert!(regenerated.contains("Vin a 0 5"), "user code preserved");
    }

    #[test]
    fn py_stimulus_roundtrip() {
        let content = write_py_stimulus(
            "test",
            SpiceBackend::NgSpice,
            ".subckt foo a b\nR1 a b 10k\n.ends",
            "",
        );
        let (header, user) = split_py(&content);
        assert!(header.contains("pyspice_rs"));
        assert!(user.contains("circuit = pyspice_rs"));
    }
}
